# Import the functions from the project code
from project import load_duck_data, check_migration_status, format_route, generate_migration_map
# Import os to check  file existence and delete files during test
import os


def test_load_duck_data():
    data = load_duck_data("migration_data.csv")

    # Test that mallard exists in data
    assert "mallard" in data

    # Check the fields for mallard
    assert data["mallard"]["migrates"] is True
    assert "november" in data["mallard"]["migration_months"]
    assert "Canada" in data["mallard"]["route"]
    assert "food" in data["mallard"]["reason"].lower()


def test_check_migration_status():
    data = load_duck_data("migration_data.csv")
    mallard = data["mallard"]

    # Check migrating and not currently migrating outputs
    assert check_migration_status(mallard, "november") == "Migrating"
    assert check_migration_status(mallard, "july") == "Not currently migrating"

    # Check does not migrate at all output
    indian_runner = data["indian runner"]
    assert check_migration_status(indian_runner, "november") == "Does not migrate"


def test_check_migration_status_invalid_month():
    data = load_duck_data("migration_data.csv")
    mallard = data["mallard"]

    # Check month not in migration months and not a valid month string
    assert check_migration_status(mallard, "invalidmonth") == "Not currently migrating"


def test_format_route():
    data = load_duck_data("migration_data.csv")
    route = data["mallard"]["route"]

    # Check the format for combining the migration locations with arrows
    formatted = format_route(route)
    assert formatted == "Canada → Great Lakes → Gulf of Mexico"


def test_generate_migration_map():
    data = load_duck_data("migration_data.csv")
    species = "mallard"
    route = data[species]["route"]

    # Expected output filename generated by the function
    expected_filename = f"{species.lower().replace(' ', '_')}_migration.png"

    # Generate the migration map image file
    generate_migration_map(species, route)

    # Assert that the image file was created
    assert os.path.exists(expected_filename), f"Map file '{expected_filename}' was not created"
    # Assert that the image file is not empty
    assert os.path.getsize(expected_filename) > 0, "Map file is empty"

    # Clean up after test
    os.remove(expected_filename)

